---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../../../openshift/cost-management/overlays/aggregate/

patches:
  - path: patch-source-and-name.yaml
    target:
      group: costmanagement-metrics-cfg.openshift.io
      kind: CostManagementMetricsConfig
      name: instance
      version: v1beta1
