apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: enable-iommu
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - iommu=pt
    - amd_iommu=on
