---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vg1
        default: true
        fstype: xfs
        deviceSelector:
          paths:
            - /dev/disk/by-path/pci-0000:41:00.0-scsi-0:0:294:0
        thinPoolConfig:
          sizePercent: 90
          name: thin-pool-1
          overprovisionRatio: 10
