apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ingress-node-firewall
  namespace: openshift-ingress-node-firewall
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: ingress-node-firewall
  source: redhat-operators
  sourceNamespace: openshift-marketplace
