kind: IngressNodeFirewallConfig
apiVersion: ingressnodefirewall.openshift.io/v1alpha1
metadata:
  name: ingressnodefirewallconfig
  namespace: openshift-ingress-node-firewall
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""