---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-defrag
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/wtcross/lab-gitops'
      targetRevision: HEAD
      path: openshift/etcd-defrag
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
