---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-openshift-virt
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/wtcross/lab-gitops'
      targetRevision: HEAD
      path: openshift/openshift-virtualization/overlays/default/
      #directory:
      #  recurse: true
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
